name: 'Apptainer Runner'
description: | 
    Run commands inside a Apptainer container (rather than Docker).

    Apptainer (or singularity) must be installed in the runner image.

inputs:
  run:
    description: 'Command to execute inside the container'
    required: true

  type:
    description: 'Type of job: container (running apptainer) or workflow (running Snakemake)'

  image:
    description: 'Image to execute the action'
    default: "ubuntu:latest"

  shell:
    description: 'Shell to execute the action'
    default: "/bin/bash"

  container_shell:
    description: 'Shell to execute the action'
    default: "/bin/bash"

  apptainer_args:
    description: 'Apptainer arguments'
    default: ""


runs:
  using: 'composite'
  steps:
    - name: Execute user's code
      shell: bash
      run: |
        RUNNER_IMAGE="${{ inputs.image }}" \
        CONTAINER_SHELL="${{ inputs.shell }}" \
        ${{ github.action_path }}/entrypoint.sh ${{ inputs.apptainer_args }} << EOF 
        ${{ inputs.run }} 
        EOF
        
    

