name: 'Apptainer Runner'
description: | 
    Run commands inside a Apptainer container (rather than Docker).

    Apptainer (or singularity) must be installed in the runner image.

inputs:
  target:
    description: 'Target of the Snakemake workflow'
    required: true

  profile:
    description: 'Profile of snakemake'
    required: false
    default: |
        cores: 1

  config:
    description: 'Configuration to execute the workflow'
    required: false
    default: |
        key: value

  upload_report:
    description: 'Whether to generate and upload the report'
    required: false
    default: 'false'

  workdir:
    description: 'Directory from which to launch Snakemake'
    required: false
    default: '.'
  
  snakefile:
    description: 'Path to the Snakefile (absolute or relateive to workdir)'
    required: false
    default: 'Snakefile'


runs:
  using: 'composite'
  steps:
    - name: Set paths
      shell: bash
      run: |
        echo "SNAKEMAKE_PROFILE=/tmp/snakemake-profiles/profile-gha-$RANDOM" >> $GITHUB_ENV
        echo "WORKFLOW_CONFIG=/tmp/workflow-configs/config-gha-$RANDOM/config.yaml" >> $GITHUB_ENV

    - name: Report snakemake version
      shell: bash
      run: |
        echo "Running Snakemake version $(snakemake --version)" >> $GITHUB_STEP_SUMMARY

    - name: Create profile
      shell: bash
      run: |
        mkdir -p $SNAKEMAKE_PROFILE
        cat <<EOF > $SNAKEMAKE_PROFILE/config.yaml
        ${{ inputs.profile }}
        EOF

    - id: create-config
      shell: bash
      run: |
        mkdir -p $(dirname $WORKFLOW_CONFIG)
        cat <<EOF > $WORKFLOW_CONFIG
        ${{ inputs.config }}
        EOF
        
            
    - name: Execute workflow
      shell: bash
      run: |
        cd ${{ inputs.workdir }}
        snakemake \
            --configfile $WORKFLOW_CONFIG \
            --snakefile ${{ inputs.snakefile }} \
            ${{ inputs.target }} 
      
    - name: Generate report
      shell: bash
      if: ${{ inputs.upload_report == 'true' }}
      run:
        cd ${{ inputs.workdir }}
        snakemake --report /tmp/report.html \
            --configfile $WORKFLOW_CONFIG \
            --snakefile ${{ inputs.snakefile }} \
            ${{ inputs.target }} 
        
    - name: Upload report
      if: ${{ inputs.upload_report == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: /tmp/report.html
        
    


